[colors.bright]
black = "0x5c6370"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "#ba8baf"
red = "0xe06c75"
white = "0xe6efff"
yellow = "0xd19a66"

[colors.dim]
black = "0x1e2127"
blue = "0x61afef"
cyan = "0x56b6c2"
green = "0x98c379"
magenta = "#ba8baf"
red = "0xe06c75"
white = "0x828791"
yellow = "0xd19a66"

[colors.normal]
black = "0x1e2127"
blue = "0x61afef"
cyan = "#1ABB9B"
green = "0x98c379"
magenta = "#ba8baf"
red = "#ab4642"
white = "0xe0def4"
yellow = "0xd19a66"

[colors.primary]
background = "0x1e2127"
bright_foreground = "0xe6efff"
foreground = "0xabb2bf"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 12

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[window]
opacity = 0.85
