require "romamihalich.options"
require "romamihalich.keymaps"
require "romamihalich.plugins"
require "romamihalich.colorscheme"

require "romamihalich.cmp"
require "romamihalich.Comment"
require "romamihalich.dashboard"
require "romamihalich.gtd"
require "romamihalich.hexokinase"
require "romamihalich.lualine"
require "romamihalich.nvim-autopairs"
require "romamihalich.nvim-lsp-installer"
require "romamihalich.nvim-tree"
require "romamihalich.nvim-treesitter"
require "romamihalich.telescope"
require "romamihalich.vimspector"
require "romamihalich.which-key"

require "romamihalich.autocommands"
