require "impatient".enable_profile()
require "romamihalich.options"
require "romamihalich.keymaps"
require "romamihalich.plugins"
require "romamihalich.colorscheme"

require "romamihalich.cmp"
require "romamihalich.Comment"
require "romamihalich.gtd"
require "romamihalich.hexokinase"
require "romamihalich.lualine"
require "romamihalich.nvim-autopairs"
require "romamihalich.lsp"
require "romamihalich.nvim-tree"
require "romamihalich.nvim-treesitter"
require "romamihalich.telescope"
require "romamihalich.nvim-dap"
require "romamihalich.which-key"

require "romamihalich.autocommands"
